### ISSUE TITLE
Pagination in Collection view not linking as expected

### ISSUE THREAD

**Issue by mraadgev** [Language-Research-Technology/oni-ui#1]
When paginating in the collection view, when you move to the next page the links are not updating to match the values displayed in the text.

See ICE for an example

**Comment by moisbo** [comment]
Hi Mark -- can you explain? I only have deployed the latest to https://data-uat.ldaca.edu.au and https://data.ldaca.edu.au.

**Comment by moisbo** [comment]
Oh got it thanks. Will fix

**Comment by moisbo** [comment]
Fixed! let me know

**Comment by mraadgev** [comment]
Confirmed, appears fixed in Firefox
