### ISSUE TITLE
Home/LDaCA button doesn't fully refresh page

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#14]
If using basic search, clicking the Home/LDaCA button will reset all the search and filters, but this doesn’t work if using advanced search - it only clears any filters you have. Same thing when clicking on Collections or Browse. I have to reload the page fully to reset it.

**Comment by moisbo** [comment]
Hi Rossana -- I'm assigning this to you so you can check. Latest code is in https://data-uat.ldaca.edu.au if all working good please feel free to close ticket

**Comment by rosanna-smith** [comment]
Thanks Moises, all working well for me!
