### ISSUE TITLE
Search Score shows in results occasionally

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#15]
When I clear a filter or I click the Home/LDaCA button after a search, the results now have a Search Score. Not immediately clear what this means or why it only shows up after clearing.

**Comment by moisbo** [comment]
This is because if you search and its sorted by relevance it will show you a score

**Comment by rosanna-smith** [comment]
Got it - maybe we should rename it to Relevance Score in that case
