### ISSUE TITLE
Access and Content sections readability

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#16]
For the Access section on an object, it might be more readable on separate lines:
You are free to:
Share - copy and redistribute the material in any medium or format.
Adapt - remix, transform, and build upon the material for any purpose, even commercially.

For the Content section in a collection, extra space above each sub-heading (Linguistic Genre, Modality, File Formats, Data licenses for access) would help readability.

**Comment by rosanna-smith** [comment]
Updating the Access section wording here since it's only one text field:
You are free to share (copy and redistribute the material in any medium or format) and adapt (remix, transform and build upon the material for any purpose, even commercially).

**Comment by moisbo** [comment]
Note that some licenses are cc-by 4 some are cc-by 3 and the text comes from:

https://creativecommons.org/licenses/by/4.0/

https://creativecommons.org/licenses/by/4.0/deed.en

https://creativecommons.org/licenses/by/3.0/

also each corpus has its license text

**Comment by rosanna-smith** [comment]
I guess there's no option in that text field to just add a <br> break paragraph or something to the original wording to get around it?

**Comment by rosanna-smith** [comment]
Full rewordings (note that I've just included the first section of the text in the link as I assume they can click through to get the full detail - as it stands these two licenses have the same wording below):

cc-by 4 https://creativecommons.org/licenses/by/4.0/
You are free to share (copy and redistribute the material in any medium or format for any purpose, even commercially), and adapt (remix, transform, and build upon the material for any purpose, even commercially). The licensor cannot revoke these freedoms as long as you follow the license terms.

cc-by 3 https://creativecommons.org/licenses/by/3.0/au/
You are free to share (copy and redistribute the material in any medium or format for any purpose, even commercially), and adapt (remix, transform, and build upon the material for any purpose, even commercially). The licensor cannot revoke these freedoms as long as you follow the license terms.

These are the two licenses I could see on the uat and main portal, but let me know if any others are needed.

**Comment by moisbo** [comment]
Fixed this so that the Access field if it comes with new lines they can be produced
