### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#20]
Some of these may be out of scope or less useful for the portal, but just adding my notes in case some of these are worth implementing:

- [ ] Generally looks like regexes only apply to the full word, so if I search for /sa/, it brings up entries with SA, but not words containing those elements like 'sat'. Searching for /marg/ doesn't return anything even though Margaret, Margo and Margie are in the data.
- [ ] Regexes don't work on phrases for me. Eg. /s[ia]t/ will give me results of ‘sit’ and ‘sat’, but if I try /s[ia]t on/ I get no results, even though examples exist.
- [ ] Regexes don’t appear to be case-sensitive, or at least, capitals don’t work. Eg. /r[a-z]{4}/ gives me highlighted results, both where r is lower and upper case (though only the first three are actually highlighted), but /R[a-z]{4}/ doesn’t return anything. Don't know how feasible it is, but we might want an option to make searches case-sensitive.
- [ ] Other regex elements that don’t appear to work: \A (beginning or string) \Z (end of a string) \b (word boundary) \B (non-word boundary) ^ (start of line) $ (end of line) and backreferencing (if this is the format those should be used in: /(s)\1/)
- [ ] Don't appear to be able to search for most punctuation/special characters, either in standard advanced search or in regex: + - = ! & etc. Escaping doesn't help.
- [ ] Escaping characters generally isn't working re. double escape issue.
- [ ] Non-regex ranges will need more testing when we have a dedicated numeric search field, eg.
- [ ] (>=10 AND <20)
- [ ] [1 TO 5]
- [ ] {* TO 2012-01-01}

**Comment by moisbo** [comment]
Yes, we'll have a look... It looks (so far) that the regex itself neeeds to be escaped also! i.e. 
```
/"/Aus/"/
```

**Comment by moisbo** [comment]
Hi @rosanna-smith 

I've applied an update to https://data-uat.ldaca.edu.au so you can see the actual query and the error handling. If you could create a list of things that you expect and things that dont work would be great.
You can modify this issue so it has checkboxes and we tick them off as we go fixing them or adding help sections
