### ISSUE TITLE
Variable ordering of object metadata

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#21]
Under the Files section, Annotation Of and Modality are ordered differently between the text and text with metadata versions - it's possible it occurs elsewhere with other metadata.

Looking at this one as an example:
https://data-uat.ldaca.edu.au/object?id=arcp%3A%2F%2Fname%2Ccorpus-of-oz-early-english%2Fitem%2F1-004&_crateId=arcp%3A%2F%2Fname%2Ccorpus-of-oz-early-english

**Comment by moisbo** [comment]
the `_source` returned from elastic is not ordered, so it needs to be sorted in some part. I will re-order it when displaying it in the oni-ui
