### ISSUE TITLE
Linguistic Genre and Sub-Collection disappear in Advanced Search

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#23]
When using Advanced search with the field Text selected, the filter for Linguistic Genre disappears in the results. It also appears not to work when searching the language field for something other than English. E.g. Searching Arabic in the language field returns results with only 6 filters available instead of 8 (linguistic genre and sub-collection missing).

**Comment by smusgrav** [comment]
Maybe because no records? Rosanna checking with testing task

**Comment by smusgrav** [comment]
Provide information to users.

**Comment by rosanna-smith** [comment]
I'm still a bit confused on why Linguistic Genre disappears in some cases where it seems that category does exist.

For example, filtering for Arabic removes Linguistic Genre, but if I go to [this object](https://data-uat.ldaca.edu.au/object?id=arcp%3A%2F%2Fname%2Ccollection-of-australian-government-documents%2Fitem%2FRelationshipStatus&_crateId=arcp%3A%2F%2Fname%2Ccollection-of-australian-government-documents&fileId=RelationshipStatus%2Fco576-1811ar.pdf) it has the genre Informational.

When I filter for Informational in Linguistic Genre, it shows me only English results (but when I click on one of the links, the other languages appear in the files section.

**Comment by moisbo** [comment]
Because the file doesnt have Linguistic Genre field. You would need to add Linguistic Genre to the file as a field

**Comment by rosanna-smith** [comment]
In that case, I wonder if the object needs updating so that it's not just English. I can't see the language metadata in the object but it seems to be showing up as only English anyway.

**Comment by moisbo** [comment]
Maybe organise a meeting with @ptsefton so we can discuss this. An object can have many files and each file has its own metadata.
