### ISSUE TITLE
Keep line breaks for View File text documents

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#25]
View File for text documents converts the new lines to space which doesn't make this version that readable, whereas downloading the file retains the line breaks. Could we update the View File view so that these breaks are kept?

**Comment by moisbo** [comment]
Hi @rosanna-smith can you tell me which example is supposed to have line breaks?

**Comment by rosanna-smith** [comment]
We could use this as an example but it would apply to all text files in the portal:
https://data-uat.ldaca.edu.au/object?id=arcp%3A%2F%2Fname%2Ccorpus-of-oz-early-english%2Fitem%2F1-112&_crateId=arcp%3A%2F%2Fname%2Ccorpus-of-oz-early-english

The downloaded file has new lines throughout, whereas the view file version doesn't and displays those as space:
https://data-uat.ldaca.edu.au/object/open?id=data%252F1-112-plain.txt&crateId=arcp%3A%2F%2Fname%2Ccorpus-of-oz-early-english

**Comment by moisbo** [comment]
great thank you : )
