### ISSUE TITLE
Include filter title in icon tooltips

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#27]
For the icons specifying file format or modality, etc. these would be clearer with the filter title appended to the tooltip as well. 
Eg:
text/plain --> File Format: text/plain
WrittenLanguage --> Modality: WrittenLanguage (or Communication Mode: WrittenLanguage if we're updating the filter name?)

**Comment by moisbo** [comment]
Hi this is a filter that comes from the metadata. So change that in each corpus so it can be re-index as you like. 

EncodingFormat comes from the actual encoding format. So not sure what to do, maybe ask Mark to add another field that is clearer and we can index that one.

**Comment by mraadgev** [comment]
@moisbo It looks like Rosanna is asking that the field name be included along with the entry for the icon tooltips rather than simply showing the values, so it appears to be more directly related to the UI rather than the data

**Comment by moisbo** [comment]
I dont get it 😄 Can you please create some sort of example? or view?

**Comment by rosanna-smith** [comment]
For this icon as an example, instead of it reading "WrittenLanguage" could we add the category title to the tooltip hover? eg. "Communication Mode: WrittenLanguage"
![Screenshot 2023-11-06 at 9 36 32 am](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/89514ad4-be55-4929-9987-877adaeb21cc)

**Comment by moisbo** [comment]
Oh! sure thing

**Comment by rosanna-smith** [comment]
thanks! sorry for the confusion, I probably should've used category instead of filter before! :)

**Comment by moisbo** [comment]
another one for you to confirm @rosanna-smith

**Comment by rosanna-smith** [comment]
Looks great, thanks!
