### ISSUE TITLE
Keep menu bar visible as you scroll pages

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#28]
Home / LDaCA logo and menu bar disappear from view when you scroll far enough down the page. Could we lock this bar so it remains and you don't have to scroll back up to access the Home button and the other links at the righthand side of the header?

**Comment by moisbo** [comment]
More for testing @rosanna-smith

**Comment by rosanna-smith** [comment]
Fantastic - looks great :)
