### ISSUE TITLE
Login restriction showing momentarily on open access data

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#29]
A login restriction can flash between pages, even if it's open access. (You do not have permission to see these files. Sign up or Login) Error can be replicated by refreshing this [link](https://data.ldaca.edu.au/object?id=arcp://name,international-corpus-of-english-australia/Document/S2A-001&_crateId=arcp://name,international-corpus-of-english-australia/S2A&fileId=S2A-001-plain.txt).

**Comment by rosanna-smith** [comment]
Still shows a red message momentarily, though it's quite fast now so hard to tell exactly what it says.

**Comment by moisbo** [comment]
Hi @rosanna-smith are you testing the UAT environment? because this link is the PROD. I havent updated prod with this only UAT

**Comment by rosanna-smith** [comment]
You're right - I checked the link above and that wasn't UAT - all fine on the UAT version, so I'll close the issue. Thanks!
