### ISSUE TITLE
Add icons to files

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#36]
On the object page, would it be possible to add the icons for file format, modality, etc. (or at least file format) to the files? It would be good to be able to see them both when the file is collapsed and expanded - possibly on the same line as the main header at the left-hand side so that it's visible for both.

![Screenshot 2023-10-30 at 9 44 53 am](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/7de43341-5101-4943-bf62-a0c0e17fa360)

![Screenshot 2023-10-30 at 9 42 13 am](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/3f6b41b1-5d30-46b9-9953-9186d2115f86)

**Comment by moisbo** [comment]
<img width="1523" alt="Screenshot 2023-12-06 at 12 28 57 pm" src="https://github.com/Language-Research-Technology/oni-ui/assets/2850269/c6912abe-02d3-4207-a9d3-95e6f3df6ec5">

Will look like this for the encodingType of the files

**Comment by rosanna-smith** [comment]
Nice! Is there any way we could add the icons next to the related file? Like the audio icon next to "Recording of Interview with Judith Eastwell (mp3)"

**Comment by moisbo** [comment]
Yes I'm making it so some icons are displayed depending on the field. This is helpful for things like binderLink 

So that next to the field we will have an icon, but it has to be different than the ones we have different style more like square boxed. I'll show later when I get them. Otis will make us more for us.

**Comment by rosanna-smith** [comment]
Another file-related issue:
Add video file format icon to main page

It looks like we don't have an icon for video files on the main page like we do for audio, pdf etc.

For example, if I filter for mp4, the results look like this:
![Screenshot 2024-02-02 at 11 24 49 am](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/07e13659-cb7a-45dd-b142-8676a401cbfa)

This one is similar to the icons we already have if we don't yet have a video icon: https://fontawesome.com/icons/file-video?f=classic&s=solid

**Comment by rosanna-smith** [comment]
And just a placeholder icon for singed language
![hands-solid](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/1a2900c5-09d5-4b33-96d0-b2344ae68d08)

**Comment by rosanna-smith** [comment]
Another thought about this, on the main page it might be good to have icons to differentiate the Types, eg. Collection, Object, File. These could work:
Collection: <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="#797979" d="M64 480H448c35.3 0 64-28.7 64-64V160c0-35.3-28.7-64-64-64H288c-10.1 0-19.6-4.7-25.6-12.8L243.2 57.6C231.1 41.5 212.1 32 192 32H64C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64z"/></svg>
Object: <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="#797979" d="M64 32C64 14.3 49.7 0 32 0S0 14.3 0 32l0 96L0 384c0 35.3 28.7 64 64 64l192 0 0-64L64 384l0-224 192 0 0-64L64 96l0-64zM288 192c0 17.7 14.3 32 32 32l224 0c17.7 0 32-14.3 32-32l0-128c0-17.7-14.3-32-32-32l-98.7 0c-8.5 0-16.6-3.4-22.6-9.4L409.4 9.4c-6-6-14.1-9.4-22.6-9.4L320 0c-17.7 0-32 14.3-32 32l0 160zm0 288c0 17.7 14.3 32 32 32l224 0c17.7 0 32-14.3 32-32l0-128c0-17.7-14.3-32-32-32l-98.7 0c-8.5 0-16.6-3.4-22.6-9.4l-13.3-13.3c-6-6-14.1-9.4-22.6-9.4L320 288c-17.7 0-32 14.3-32 32l0 160z"/></svg>
File: <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path fill="#797979" d="M0 64C0 28.7 28.7 0 64 0L224 0l0 128c0 17.7 14.3 32 32 32l128 0 0 288c0 35.3-28.7 64-64 64L64 512c-35.3 0-64-28.7-64-64L0 64zm384 64l-128 0L256 0 384 128z"/></svg>
