### ISSUE TITLE
Remove property from Type in Collections

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#37]
Could we update the Type section of Collections on the main page so that only RepositoryCollection is showing, rather than both that and Datset for example?

**Comment by rosanna-smith** [comment]
Screenshot for the relevant section:
![Screenshot 2023-11-09 at 2 11 33 pm](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/a0bc51d4-f690-408e-b00f-51b38e645510)

**Comment by moisbo** [comment]
This will get fixed when we create a new type for displaying and decide which new type to display with the [metadata migration](https://github.com/orgs/Language-Research-Technology/projects/6)
