### ISSUE TITLE
Change Help to be a customisable sub-menu

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/oni-ui#39]
@smusgrav 

- [x] Customisable links in sub-menu
- [x] And a default about page that could be omitted -- Instead of this I  made an about page and then subsequent links can be added. The about page can be changed in config

Default page:
---

This portal was built with [Oni](https://github.com/Arkisto-Platform/oni), a web application which provides indexing, searching and access to secure data repositories which follow the Arkisto model.
[Arkisto]([Arkisto ([arkisto-platform.github.io](http://arkisto-platform.github.io/))](https://arkisto-platform.github.io/)) is a scalable, standards based platform for sustainable data which takes as its basis  that the long-term preservability of well-described data is _always_ the first consideration. Arkisto is based on open standards for research object metadata - [RO-Crate](https://www.researchobject.org/),  and file based repositories - [OCFL](https://ocfl.io/).
Oni provides a web browser interface to Arkisto-compliant data and metadata. It uses [Elastic Search](https://www.elastic.co/) for indexing and searching; it handles authorization with [CILogon]((https://ca.cilogon.org/)) and access management with [REMS - Resource Entitlement Management System](https://github.com/CSCfi/rems).

---

**Comment by moisbo** [comment]
For you to test @rosanna-smith these links can be modified in configuration.json the ones after the api.

**Comment by rosanna-smith** [comment]
@smusgrav for further review. The dropdowns under Help look good to me.

**Comment by smusgrav** [comment]
I'm happy.
