### ISSUE TITLE
When advancing the pages the Sort changes to Relevance

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/oni-ui#40]
If you load the page Sorts by collections, but then when you click on pages it changes to Relevance, giving the sense that there is no match between pages and cannot go back!

**Comment by rosanna-smith** [comment]
I see what you mean! Hadn't noticed that before but that happens when I test it as well.

**Comment by moisbo** [comment]
Hi @rosanna-smith I made a little change that fixes this. Hopefully I didnt break anything else! Would you mind testing please?

**Comment by rosanna-smith** [comment]
Works well for me :)
