### ISSUE TITLE
Tooltip text not appearing on hover

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#43]
Help text on collection and object pages don't appear on hover like they do on the main page. Instead you have to click on them for the info to appear.
![Screenshot 2023-11-10 at 9 48 12 am](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/3dda72a2-5a97-4799-b35b-4938950fd18a)

**Comment by moisbo** [comment]
Yes, it was requested like that to click on the help field
