### ISSUE TITLE
Search/Filter Text Box for Objects

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#50]
Similar to the Filter box in the dropdown filters on the main page, would it be possible to have a Filter box in the Objects section of a collections page so that items are easier to find in larger collections?
![Screenshot 2023-11-17 at 9 28 44 am](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/187686ba-52a8-4a45-bcab-7ce8939fe25b)
![Screenshot 2023-11-17 at 9 30 44 am](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/8774c16f-1d6a-4a5e-b296-e631051bcfa5)

**Comment by moisbo** [comment]
No not really this is a subset of a search that is why More goes to search with that filter

**Comment by rosanna-smith** [comment]
Ok, the users found that section quite hard to navigate when they wanted to find a particular item - is there anything else we could add there to help if not a search? Maybe a sort/order by?

**Comment by moisbo** [comment]
Not really they can click more and go back to search that search is already filtered
