### ISSUE TITLE
Crate wasn't downloading for me but that could just be a single user issue

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/oni-ui#76]
I'm assuming this is in the collection page? in the Download Metadata. Is that correct @rosanna-smith ?

**Comment by rosanna-smith** [comment]
Yes, that's correct.

**Comment by moisbo** [comment]
So something like:

Here does not work:
https://demo.ldaca.edu.au/api/object/https%3A%2F%2Fcatalog.paradisec.org.au%2Frepository%2FTD1?resolve-parts=&noUrid=&meta=remote

and 

Here works:
https://data-uat.ldaca.edu.au/api/object/arcp%3A%2F%2Fname%2Ccollection-of-australian-government-documents?resolve-parts=&noUrid=&meta=original

is it that meta=original? @alvinsw ?

**Comment by moisbo** [comment]
fixed
