### ISSUE TITLE
Filters return errors with the total results if they are applied one by one, eg. Collection: Papua New Guinean Languages (258) --> Language: Motu (16) returns 1454 entries and some are out of bounds, whereas applying these two at the same time gives also incorrect 2798 entries. List view correctly gives 16 results.

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/oni-ui#77]
Hi Rosanna, Can you explain how to replicate?

**Comment by rosanna-smith** [comment]
https://demo.ldaca.edu.au
In list view:
Test 1:
- Select the filters 'Papua New Guinean Languages' under Collection and 'Motu' under Language
- Apply Filters
**- Total results: 16**
Test 2:
- Select the filter 'Papua New Guinean Languages' under Collection and Apply Filter (1147 results)
- Select the filter 'Motu' under Language and Apply Filter
**- Total results: 16**
In list view:
Test 1:
- Select the filters 'Papua New Guinean Languages' under Collection and 'Motu' under Language
- Apply Filters
**- Total results: 1311**
Test 2:
- Select the filter 'Papua New Guinean Languages' under Collection and Apply Filter (253 results)
- Select the filter 'Motu' under Language and Apply Filter
**- Total results: 1311**

**Comment by moisbo** [comment]
gotcha can reproduce. I'm having a look

**Comment by rosanna-smith** [comment]
Tested - that's working fine now :)
