### ISSUE TITLE
Basic search: "island" gives 199 results in list view, but 81 in map view (probably because it always focuses only on Australia and not the extent of the search)

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/oni-ui#78]
The map search focuses on map filtering so you search within the bounds unless that is a UX problem. So expand the bounds or I can change the logic to dont care about the bounds when searching

**Comment by rosanna-smith** [comment]
Yeah, for searching we probably don't want the bounds, because when you first go to the map I'd expect it to start in the same state as the list view with everything and be able to narrow the search or filters from there.

**Comment by moisbo** [comment]
We cannot have a not bounds search because otherwise the map search engine will not search anything. The search needs bounds to search within some bounds

**Comment by rosanna-smith** [comment]
Solution addressed in https://github.com/Language-Research-Technology/oni-ui/issues/81
