### ISSUE TITLE
Switching views with a search or filter resets everything rather than just displaying the results in the other view.

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/oni-ui#79]
Yes this is how I designed it. No interconnection between the List or Map search

**Comment by rosanna-smith** [comment]
All good then - maybe we should clarify this in a hover tooltip for list and map view. Something like "View the results as blah blah. Note that current search and filter options will be reset."

**Comment by moisbo** [comment]
Sounds good I will add a hover tooltip
