### ISSUE TITLE
Maps view by default limits the results, eg. if I filter Japanese from the list view it appears, but if I reset completely, and select map view, Japanese doesn't appear at all since it doesn't occur in Australian where the map defaults to. (List view with no filters: 33291 results, Map view with no filters: 1311, but it should actually be at least 3400)

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/oni-ui#81]
Yes this is similar to #78 The search is within the bounds, because I need bounds information to search on

**Comment by moisbo** [comment]
Do this as a test... Zoom out the whole world in google maps. now search for "tacos" will it bring the whole world of where are the tacos?

**Comment by rosanna-smith** [comment]
Zooming out fully on the map still doesn't show the full set of filter options though, e.g if I zoom out from Australia, Language filter changes from 345 to 544, but if I drag the map left or right, the number changes, so there's no way to view the full list of filter options (687) in map view.

**Comment by rosanna-smith** [comment]
Tested the demo version with searching for 'house' zoomed out - this gives 34 results, but there are more in the map not shown when I move it around.

**Comment by moisbo** [comment]
Yes, this is because you cannot zoom out and get all of the world in one view that could fit in the map

**Comment by rosanna-smith** [comment]
Maybe we need a note somewhere on the map saying something like the filter and search results will only show results on the current map view, move or resize the map to view other results.
