### ISSUE TITLE
Differing results for Boolean operators

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/oni-ui#92]
If this should go in auto-ldaca-data-portals let me know and I'll move it.

I'm putting together some training around advanced search in the portal, and noticed some differences in result count for boolean operators. I'm testing three types here:
1) two terms in a single search field without parentheses
![Screenshot 2024-06-26 at 3 04 47 pm](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/d6e95c60-41e9-4c3b-81f1-43c51a425685)
2) two terms in a single search field with parentheses
![Screenshot 2024-06-26 at 3 05 00 pm](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/f5b96d59-d937-4a87-b02d-7395c63654c1)
3) two terms in separate search fields with the boolean operator.
![Screenshot 2024-06-26 at 3 04 26 pm](https://github.com/Language-Research-Technology/oni-ui/assets/143474414/09f9c782-fdff-445b-974f-2f6c664d5cc3)

I'm including the searches and results I got from each below, together with the query output, which seems to be slightly different for each.

**AND:**

otway AND grampians: 0 results
( name.@value : otway AND grampians OR description.@value : otway AND grampians OR inLanguage.name.@value : otway AND grampians OR _text : otway AND grampians   )  

(otway AND grampians): 1 result
( name.@value : (otway AND grampians) OR description.@value : (otway AND grampians) OR inLanguage.name.@value : (otway AND grampians) OR _text : (otway AND grampians)   )

Text 1: otway /AND/ Text 2: grampians: 1 result
( name.@value : otway OR description.@value : otway OR inLanguage.name.@value : otway OR _text : otway   ) AND ( name.@value : grampians OR description.@value : grampians OR inLanguage.name.@value : grampians OR _text : grampians   ) 

**OR:**

otway OR grampians: 9 results
( name.@value : otway OR grampians OR description.@value : otway OR grampians OR inLanguage.name.@value : otway OR grampians OR _text : otway OR grampians   )

(otway OR grampians): 14 results
( name.@value : (otway OR grampians) OR description.@value : (otway OR grampians) OR inLanguage.name.@value : (otway OR grampians) OR _text : (otway OR grampians)   ) 

Text 1: otway /OR/ Text 2: grampians: 14 results
( name.@value : otway OR description.@value : otway OR inLanguage.name.@value : otway OR _text : otway   ) OR ( name.@value : grampians OR description.@value : grampians OR inLanguage.name.@value : grampians OR _text : grampians   )

**NOT:**

otway NOT grampians: 9 results
( name.@value : otway NOT grampians OR description.@value : otway NOT grampians OR inLanguage.name.@value : otway NOT grampians OR _text : otway NOT grampians   )

(otway NOT grampians): 8 results
( name.@value : (otway NOT grampians) OR description.@value : (otway NOT grampians) OR inLanguage.name.@value : (otway NOT grampians) OR _text : (otway NOT grampians)   )

Text 1: otway /NOT/ Text 2: grampians: 8 results
( name.@value : otway OR description.@value : otway OR inLanguage.name.@value : otway OR _text : otway   ) NOT ( name.@value : grampians OR description.@value : grampians OR inLanguage.name.@value : grampians OR _text : grampians   ) 

Options 2 and 3 provide identical results, so it seems like it's booleans without parentheses that are producing different counts. The help says to use parentheses when multiple operators are used, but seems like it's required for a single operator as well.

**Comment by moisbo** [comment]
Hi Rosanna -- Have a look at what query is produced with the Show Query Button and then try to reproduce it with the API. If there is a difference then we should address it, otherwise I'd update the help page. I mean a difference with the results, because there might be a bug on the query generation **or** that is how opensearch works

1. With postman create a query with the API
2. Compare it to what is produced as a query
3. Run the query in both

**Comment by rosanna-smith** [comment]
Adding my results from comparing searches on Postman:

Query | Portal | Postman API
--- | --- | ---
otway AND grampians | 0 | 0
(otway AND grampians) | 1 |  1
Text 1: otway /AND/ Text 2: grampians | 1 | 1
otway OR grampians | 9 | 9
(otway OR grampians) | 14 | 14
Text 1: otway /OR/ Text 2: grampians | 14 | 14
otway NOT grampians | 9 | 9
(otway NOT grampians) | 8 | 8
Text 1: otway /NOT/ Text 2: grampians | 8 | 8

All the results match between the two, so looks like the queries don't produce accurate results if no brackets are used around a query. I'll update this in the docs so it's clear this method shouldn't be used.

**Comment by rosanna-smith** [comment]
@moisbo just to remind myself on the processes - the updates to the advanced help are now merged to the main branch of oni-ui, but there are other steps before we'd expect to see those updates on the actual portal, correct?

**Comment by moisbo** [comment]
Yep. It's not automated. We need to run ansible scripts

----
Software Developer
Z: https://uqz.zoom.us/my/moises.sacal
________________________________
